const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Behaviors.Platform,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Dictionary.Acts.Clear
	];
};
self.C3_JsPropNameTable = [
	{CannonFrame: 0},
	{Barrel: 0},
	{Fuse: 0},
	{CannonSmoke: 0},
	{Tween: 0},
	{ViewExpansion: 0},
	{PidgeonSpawn: 0},
	{CannonLoadTrigger: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{CityBackground: 0},
	{PlayerScores: 0},
	{PlayerScoreValues: 0},
	{SkipWinner: 0},
	{Anchor: 0},
	{Winner: 0},
	{winnerBackground: 0},
	{Restart: 0},
	{Platform: 0},
	{Pidgeon: 0},
	{Keyboard: 0},
	{Audio: 0},
	{cannonDeg: 0},
	{Bullet: 0},
	{firedPidgeon: 0},
	{MinimalTileset: 0},
	{GameRules: 0},
	{owner: 0},
	{PlayerBalloon: 0},
	{FeatherExplosion: 0},
	{PopConfetti: 0},
	{scale: 0},
	{idle: 0},
	{inCannon: 0},
	{inFlight: 0},
	{winner: 0}
];

self.InstanceType = {
	CannonFrame: class extends self.ISpriteInstance {},
	Barrel: class extends self.ISpriteInstance {},
	Fuse: class extends self.ISpriteInstance {},
	CannonSmoke: class extends self.IParticlesInstance {},
	ViewExpansion: class extends self.ISpriteInstance {},
	PidgeonSpawn: class extends self.ISpriteInstance {},
	CannonLoadTrigger: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	CityBackground: class extends self.ITiledBackgroundInstance {},
	PlayerScores: class extends self.ITextInstance {},
	PlayerScoreValues: class extends self.IDictionaryInstance {},
	SkipWinner: class extends self.IButtonInstance {},
	Winner: class extends self.ITextInstance {},
	winnerBackground: class extends self.ITiledBackgroundInstance {},
	Restart: class extends self.IButtonInstance {},
	Pidgeon: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	cannonDeg: class extends self.ITextInstance {},
	firedPidgeon: class extends self.ISpriteInstance {},
	MinimalTileset: class extends self.ITilemapInstance {},
	GameRules: class extends self.ITextInstance {},
	PlayerBalloon: class extends self.ISpriteInstance {},
	FeatherExplosion: class extends self.IParticlesInstance {},
	PopConfetti: class extends self.IParticlesInstance {}
}